initvals: fix compiler error caused by a missing include
[juhosg@idared initvals-tool]$ make all
gcc  -o initvals initvals.c
initvals.c: In function ‘ar9580_1p0_hw_print_initvals’:
initvals.c:476: error: ‘ar9580_1p0_modes_fast_clock’ undeclared (first use in this function)
initvals.c:476: error: (Each undeclared identifier is reported only once
initvals.c:476: error: for each function it appears in.)
<...>

Signed-off-by: Gabor Juhos <juhosg@openwrt.org>